addSbtPlugin("com.github.sbt"          % "sbt-release"         % "1.4.0")
addSbtPlugin("com.github.sbt"          % "sbt-pgp"             % "2.2.1")
addSbtPlugin("org.xerial.sbt"          % "sbt-sonatype"        % "3.11.3")
addSbtPlugin("com.timushev.sbt"        % "sbt-updates"         % "0.6.3")
addSbtPlugin("com.github.sbt"          % "sbt-native-packager" % "1.10.4")
addSbtPlugin("ch.epfl.scala"           % "sbt-scalafix"        % "0.13.0")
addSbtPlugin("org.playframework.twirl" % "sbt-twirl"           % "2.0.7")
