addSbtPlugin("com.github.sbt"   % "sbt-release"         % "1.1.0")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"             % "2.1.2")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"        % "3.9.7")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.5.3")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.8.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-twirl"           % "1.5.1")
