name: Scala CI Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

    - name: Run tests
      run: sbt test
    
    - name: Package
      run: sbt universal:packageZipTarball

    - name: Copy artifact
      run: cp target/universal/*.tgz code-examples-manager-${{steps.get_version.outputs.VERSION}}.tgz

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: code-examples-manager-${{steps.get_version.outputs.VERSION}}.tgz
        path: code-examples-manager-${{steps.get_version.outputs.VERSION}}.tgz

    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
      env:
        GHR_PATH: code-examples-manager-${{steps.get_version.outputs.VERSION}}.tgz
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
